# MCMMO Credits Example Configuration
# Repository: https://github.com/CultivateGames/MCMMOCreditsExample
# MCMMOCredits: https://github.com/CultivateGames/MCMMOCredits
# Wiki: https://github.com/CultivateGames/MCMMOCredits/wiki/

blocks:
- STONE
- SAND
- DIRT
- GRASS_BLOCK
use-event: false
amount: 1
operation: ADD
